### ISSUE TITLE
Installation Guide?

### ISSUE THREAD

**Issue by SarkarKurdish** [Aleksbgbg/Streamfox.Server#2]
Hey, thanks for this great project I can't find an installation Guide is there is any?

**Comment by Aleksbgbg** [comment]
Hi @SarkarKurdish, sorry for the late response, never saw this issue - there isn't one at the moment and no plan to implement one from my side. If you want to write one though, feel free to send a pull request.

It's not really an installable project, you build the server and the client and place them in appropriate directories. Perhaps you can create a script that does this automatically.

**Comment by Aleksbgbg** [comment]
Since the project has moved forward quite a bit since my last message, I have created a full description of the necessary steps at https://github.com/Aleksbgbg/streamfox/issues/13.
